id: tudelft-3d-opencities
title: TU Delft 3D Open Cities Portal
description: "A comprehensive catalog of open 3D city model datasets from around the world.\nCurated by the 3D Geoinformation Research Group at TU Delft.\nThis catalog aggregates CityJSON and CityGML datasets from various cities and regions.\n"
collections:
- american-cities-config.yaml
- netherlands-3d-bag-config.yaml
- estonia-config.yaml
- hamburg-config.yaml
- ingolstadt-config.yaml
- japan-plateau-config.yaml
- linz-config.yaml
- luxembourg-config.yaml
- montreal-config.yaml
- namur-config.yaml
- new-york-doitt-config.yaml
- new-york-tum-config.yaml
- rotterdam-config.yaml
- singapore-config.yaml
- the-hague-config.yaml
- vantaa-config.yaml
- zurich-config.yaml
- baden-wurttemberg-lgl.yaml
- bavaria-bvv.yaml
- brandenburg-lgb.yaml
- bremen-geobremen.yaml
- freiburg-stadt.yaml
- hannover-stadt.yaml
- kuopio-municipal.yaml
- poznan-geopoz.yaml
- prague-ipr.yaml
- riga-georiga.yaml
- auvergne-rhone-alpes-eleven-sectors-craig-config.yaml
- auvergne-rhone-alpes-zae-craig-config.yaml
- chatel-guyon-riom-craig-config.yaml
- clermont-ferrand-craig-config.yaml
- hessen-hvbg-config.yaml
- isere-craig-config.yaml
- leipzig-stadt-config.yaml
- niedersachsen-lgln-config.yaml
- nordrhein-westfalen-geobasis-config.yaml
- rheinland-pfalz-lvermgeo-config.yaml
- sachsen-anhalt-lvermgeo-config.yaml
- sachsen-geosn-config.yaml
- schleswig-holstein-lvermgeo-config.yaml
- vichy-unesco-craig-config.yaml
- bordeaux-config.yaml
- melbourne-config.yaml
- toronto-config.yaml
- wellington-config.yaml
# These are not valid, actual data not found or not publicly accessible
# - mecklenburg-vorpommern-laiv-config.yaml
# - berlin-config.yaml
# - brussels-config.yaml
# - dresden-config.yaml
# - espoo-config.yaml
# - helsinki-config.yaml
# - lyon-config.yaml
# - north-rhine-westphalia-config.yaml
# - potsdam-config.yaml
# - vienna-config.yaml
