id: new-york-doitt-3d
title: New York City 3D Building Models (LoD2) by DoITT
description: "3D LoD2 building models of New York City by the Department of Information Technology & Telecommunications (DoITT).\nCreated from cadastre footprints combined with LiDAR data.\nBuildings are modeled with thematic surfaces in LoD2, though for most buildings the geometric shape is LoD1.\nAvailable in CityGML, ESRI Multipatch, and DGN formats.\n"
license: CC-BY-4.0
keywords:
- 3d city model
- buildings
- LOD2
- United States
- New York City
- CityGML
- LiDAR
- DoITT
providers:
- name: NYC DoITT
  url: https://www1.nyc.gov/site/doitt/index.page
  roles:
  - producer
  - licensor
  description: NYC Department of Information Technology & Telecommunications
- name: TU Delft 3D Geoinformation
  url: https://3d.bk.tudelft.nl/
  roles:
  - host
  description: 3D Geoinformation Research Group at TU Delft
  inputs: []
extent:
  spatial:
    bbox: []
    crs: EPSG:2263
  temporal:
    start: '2016-01-01T00:00:00Z'
    end: '2016-12-31T23:59:59Z'
links:
- rel: about
  href: https://3d.bk.tudelft.nl/opendata/opencities/
  type: text/html
  title: TU Delft 3D Open Cities Portal
- rel: source
  href: https://www1.nyc.gov/site/doitt/initiatives/3d-building.page
  type: text/html
  title: NYC 3D Building Models Official Page
