id: new-york-doitt-3d
title: New York City 3D Building Models (LoD2) by NYC OTI
description: "3D LoD2 building models of New York City by the Office of Technology and Innovation (OTI, formerly DoITT).\nCreated from cadastre footprints combined with LiDAR data.\nBuildings are modeled with thematic surfaces in LoD2, though for most buildings the geometric shape is LoD1.\nAvailable in CityGML, ESRI Multipatch, and DGN formats.\n"
license: OTHER
keywords:
- 3d city model
- buildings
- LOD2
- United States
- New York City
- CityGML
- LiDAR
- OTI
providers:
- name: NYC Office of Technology and Innovation (OTI)
  url: https://www.nyc.gov/assets/cto/
  roles:
  - producer
  - licensor
  description: NYC Office of Technology and Innovation (formerly DoITT)
inputs:
  - https://3d.bk.tudelft.nl/opendata/cityjson/3dcities/v2.0/DA13_3D_Buildings_Merged.city.json
  # - https://3d.bk.tudelft.nl/opendata/cityjson/3dcities/citygml/DA13_3D_Buildings_Merged.gml
extent:
  spatial:
    bbox: []
    crs: EPSG:2263
  temporal:
    start: '2014-01-01T00:00:00Z'
    end: '2014-12-31T23:59:59Z'
links:
- rel: about
  href: https://3d.bk.tudelft.nl/opendata/opencities/
  type: text/html
  title: TU Delft 3D Open Cities Portal
- rel: source
  href: https://data.cityofnewyork.us/City-Government/3-D-Building-Model/tnru-abg2
  type: text/html
  title: NYC 3D Building Model (NYC Open Data)
- rel: source
  href: https://www.nyc.gov/site/planning/data-maps/open-data/dwn-nyc-3d-model-download.page
  type: text/html
  title: NYC 3D Model by Community District (DCP)
- rel: license
  href: https://www.nyc.gov/home/terms-of-use.page
  type: text/html
  title: NYC.gov Terms of Use
