# NOTE: webpage doesn't exist anymore
id: north-rhine-westphalia-3d
title: North Rhine-Westphalia 3D Building Models (LoD1+LoD2)
description: "Enormous 3D building dataset covering the entire state of North Rhine-Westphalia (NRW), Germany.\nNRW is the most populated state in Germany. Cities included: Düsseldorf, Essen, Oberhausen,\nKöln (Cologne), Bonn, and many more.\nCreated from cadastre footprints, LiDAR, and aerial images.\nLoD1 is derived from LoD2 models with average roof height.\nAvailable in CityGML format.\n"
license: dl-de/zero-2-0
keywords:
- 3d city model
- buildings
- LOD1
- LOD2
- Germany
- NRW
- North Rhine-Westphalia
- CityGML
- state-wide
- multi-city
- LiDAR
providers:
- name: Land Nordrhein-Westfalen
  url: https://www.land.nrw/
  roles:
  - producer
  - licensor
  description: North Rhine-Westphalia state government
- name: Open.NRW
  url: https://open.nrw/
  roles:
  - host
  description: Official open data portal of North Rhine-Westphalia
inputs: []
extent:
  spatial:
    bbox: []
    crs: EPSG:25832
  temporal:
    start: '2016-01-01T00:00:00Z'
    end: '2019-12-31T23:59:59Z'
links:
- rel: alternate # update
  href: https://www.gis.nrw.de/geobasis/LOD2/SceneServer
  type: application/json
  title: 3D Scene Server API for web visualization
- rel: source
  href: https://open.nrw/
  type: text/html
  title: Open.NRW - Official Open Data Portal
- rel: alternate
  href: https://geoportal.nrw/
  type: text/html
  title: Geoportal.NRW
- rel: alternate
  href: https://3d.bk.tudelft.nl/opendata/opencities/
  type: text/html
  title: TU Delft 3D Open Cities Portal (host)
- rel: license
  href: https://www.govdata.de/dl-de/zero-2-0
  type: text/html
  title: Datenlizenz Deutschland - Zero - Version 2.0
