# It's not CityGML, CityJSON
id: potsdam-3d
title: Potsdam 3D City Model (LoD2)
description: "3D LoD2 city model of Potsdam, Germany.\nAvailable in CityGML format.\n"
license: dl-de/by-2-0
keywords:
- 3d city model
- buildings
- LOD2
- Germany
- Potsdam
- CityGML
- GeoJSON
providers:
- name: Landeshauptstadt Potsdam
  url: https://www.potsdam.de/
  roles:
  - producer
  - licensor
  description: Potsdam municipality - Official city government
inputs:
  - https://opendata.potsdam.de/api/explore/v2.1/catalog/datasets/3d-gebaudemodell-lod2-citygml/exports/geojson?lang=en&timezone=Europe%2FBerlin&epsg=25833
extent:
  spatial:
    bbox: []
    crs: EPSG:25833
  temporal:
    start: '2018-01-01T00:00:00Z'
    end: '2018-12-31T23:59:59Z'
links:
- rel: source 
  href: https://opendata.potsdam.de/pages/home/
  type: text/html
  title: Open Data Portal of the state capital Potsdam
- rel: source
  href: https://geoportal.brandenburg.de/
  type: text/html
  title: Geoportal Brandenburg (state geoportal)
- rel: alternate
  href: https://3d.bk.tudelft.nl/opendata/opencities/
  type: text/html
  title: TU Delft 3D Open Cities Portal (host)
- rel: license
  href: https://www.govdata.de/dl-de/by-2-0
  type: text/html
  title: Datenlizenz Deutschland - Namensnennung - Version 2.0
