version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - cityjson-stac-cargo:/usr/local/cargo
      - cityjson-stac-target:/workspaces/cityjson-stac/target

    # Override the container user to vscode
    user: vscode

    # Use forwardPorts to expose ports within the container
    # Add the port mappings to the **devcontainer.json** forwardPorts attribute
    ports:
      - "8080:8080"
      - "3000:3000"

    # Mounts for git
    mounts:
      - type: bind
        source: ${HOME}/.gitconfig
        target: /home/vscode/.gitconfig
      - type: bind
        source: ${HOME}/.ssh
        target: /home/vscode/.ssh

    # Keeps the container running
    command: sleep infinity

    # Runs container as privileged for debugging
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Environment variables
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1

volumes:
  cityjson-stac-cargo:
  cityjson-stac-target:
